name: Test

on:
  push:
    branches:
      - main
  pull_request:



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          cache-dependency-path: 'yarn.lock'
      
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
        
      - name: Install Node dependencies
        run: |
          yarn

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Compile Contracts
        run: |        
          yarn compile:l2
          yarn compile:l1
      
      - name: Run devnet
        run: |
          yarn testnet:l2 &
          yarn testnet:l1 &
     
      - name: Run tests
        run: |
          npx hardhat test test/messaging.test.ts
          npx hardhat test test/verify_signature.test.ts
          
      